"""add keywords column to text_embeddings

Revision ID: 05a8b68c724f
Revises: 46344f09af22
Create Date: 2026-02-27 10:33:49.587594

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "05a8b68c724f"
down_revision: str | Sequence[str] | None = "46344f09af22"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("idx_products_fts"),
        table_name="products",
        schema="agent_v1",
        postgresql_using="gin",
    )
    op.add_column(
        "text_embeddings",
        sa.Column(
            "keywords",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="[]",
        ),
        schema="agent_v1",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("text_embeddings", "keywords", schema="agent_v1")
    op.create_index(
        op.f("idx_products_fts"),
        "products",
        [
            sa.literal_column(
                "to_tsvector('simple'::regconfig, "
                "(COALESCE(name, ''::character varying)::text || ' '::text) || "
                "COALESCE(description, ''::text))"
            )
        ],
        unique=False,
        schema="agent_v1",
        postgresql_using="gin",
    )
    # ### end Alembic commands ###
