"""add_hitl_tables

Revision ID: 06239365eee6
Revises: f8a2c1d3e5b7
Create Date: 2026-03-08 12:20:47.359431

"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "06239365eee6"
down_revision: str | Sequence[str] | None = "f8a2c1d3e5b7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hitl_metadata",
        sa.Column("pause_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.String(length=100), nullable=False),
        sa.Column("pause_reason", sa.String(length=50), nullable=False),
        sa.Column("paused_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("timeout_notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("escalated_to_support_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("admin_id", sa.String(length=100), nullable=True),
        sa.Column("escalation_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("pause_id"),
        schema="agent_v1",
    )
    op.create_index(
        op.f("ix_agent_v1_hitl_metadata_session_id"),
        "hitl_metadata",
        ["session_id"],
        unique=False,
        schema="agent_v1",
    )
    op.create_index(
        "ix_hitl_metadata_status_paused",
        "hitl_metadata",
        ["status", "paused_at"],
        unique=False,
        schema="agent_v1",
    )
    op.create_table(
        "interrupted_sessions",
        sa.Column("session_id", sa.String(length=100), nullable=False),
        sa.Column("next_node", sa.String(length=100), nullable=False),
        sa.Column("reason", sa.String(length=50), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("admin_id", sa.String(length=100), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("escalation_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("session_id"),
        schema="agent_v1",
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.String(length=100), nullable=False),
        sa.Column("customer_id", sa.String(length=100), nullable=False),
        sa.Column("order_info", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="agent_v1",
    )
    op.create_index(
        op.f("ix_agent_v1_orders_created_at"),
        "orders",
        ["created_at"],
        unique=False,
        schema="agent_v1",
    )
    op.create_index(
        op.f("ix_agent_v1_orders_customer_id"),
        "orders",
        ["customer_id"],
        unique=False,
        schema="agent_v1",
    )
    op.create_index(
        op.f("ix_agent_v1_orders_session_id"),
        "orders",
        ["session_id"],
        unique=False,
        schema="agent_v1",
    )
    op.create_table(
        "queued_messages",
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.String(length=100), nullable=False),
        sa.Column("message_text", sa.Text(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("message_id"),
        schema="agent_v1",
    )
    op.create_index(
        op.f("ix_agent_v1_queued_messages_received_at"),
        "queued_messages",
        ["received_at"],
        unique=False,
        schema="agent_v1",
    )
    op.create_index(
        op.f("ix_agent_v1_queued_messages_session_id"),
        "queued_messages",
        ["session_id"],
        unique=False,
        schema="agent_v1",
    )
    op.create_index(
        "ix_queued_messages_session_proc_time",
        "queued_messages",
        ["session_id", "processed", "received_at"],
        unique=False,
        schema="agent_v1",
    )
    op.create_table(
        "review_actions",
        sa.Column("action_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.String(length=100), nullable=False),
        sa.Column("pause_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("state_edits", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reason_or_comment", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("admin_user_id", sa.String(length=100), nullable=False),
        sa.Column("expected_version", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("action_id"),
        sa.UniqueConstraint("idempotency_key", name="uq_review_actions_idempotency"),
        schema="agent_v1",
    )
    op.create_index(
        op.f("ix_agent_v1_review_actions_session_id"),
        "review_actions",
        ["session_id"],
        unique=False,
        schema="agent_v1",
    )
    op.create_table(
        "support_queue",
        sa.Column("queue_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.String(length=100), nullable=False),
        sa.Column("reason", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("assigned_to", sa.String(length=100), nullable=True),
        sa.Column("context_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("queue_id"),
        sa.UniqueConstraint("session_id", name="uq_support_queue_session"),
        schema="agent_v1",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("support_queue", schema="agent_v1")
    op.drop_index(
        op.f("ix_agent_v1_review_actions_session_id"),
        table_name="review_actions",
        schema="agent_v1",
    )
    op.drop_table("review_actions", schema="agent_v1")
    op.drop_index(
        "ix_queued_messages_session_proc_time", table_name="queued_messages", schema="agent_v1"
    )
    op.drop_index(
        op.f("ix_agent_v1_queued_messages_session_id"),
        table_name="queued_messages",
        schema="agent_v1",
    )
    op.drop_index(
        op.f("ix_agent_v1_queued_messages_received_at"),
        table_name="queued_messages",
        schema="agent_v1",
    )
    op.drop_table("queued_messages", schema="agent_v1")
    op.drop_index(op.f("ix_agent_v1_orders_session_id"), table_name="orders", schema="agent_v1")
    op.drop_index(op.f("ix_agent_v1_orders_customer_id"), table_name="orders", schema="agent_v1")
    op.drop_index(op.f("ix_agent_v1_orders_created_at"), table_name="orders", schema="agent_v1")
    op.drop_table("orders", schema="agent_v1")
    op.drop_table("interrupted_sessions", schema="agent_v1")
    op.drop_index("ix_hitl_metadata_status_paused", table_name="hitl_metadata", schema="agent_v1")
    op.drop_index(
        op.f("ix_agent_v1_hitl_metadata_session_id"), table_name="hitl_metadata", schema="agent_v1"
    )
    op.drop_table("hitl_metadata", schema="agent_v1")
    # ### end Alembic commands ###
