"""add_memory_tables

Revision ID: 210f1c8a8652
Revises: 97ac54f75227
Create Date: 2026-03-29 10:51:17.819298

"""

from __future__ import annotations

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "210f1c8a8652"
down_revision: str | None = "97ac54f75227"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation_summaries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.String(length=100), nullable=False),
        sa.Column("thread_id", sa.String(length=100), nullable=False),
        sa.Column("summary_text", sa.Text(), nullable=False),
        sa.Column("products_discussed", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("customer_preference", sa.String(length=500), nullable=True),
        sa.Column("budget_stated", sa.String(length=100), nullable=True),
        sa.Column("open_questions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("summary_model", sa.String(length=100), nullable=False),
        sa.Column("summary_version", sa.Integer(), nullable=False),
        sa.Column("checkpoint_id", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("customer_id", "thread_id", name="uq_summary_customer_thread"),
        schema="agent_v1",
    )
    op.create_index(
        op.f("ix_agent_v1_conversation_summaries_created_at"),
        "conversation_summaries",
        ["created_at"],
        unique=False,
        schema="agent_v1",
    )
    op.create_index(
        op.f("ix_agent_v1_conversation_summaries_customer_id"),
        "conversation_summaries",
        ["customer_id"],
        unique=False,
        schema="agent_v1",
    )
    op.create_index(
        op.f("ix_agent_v1_conversation_summaries_thread_id"),
        "conversation_summaries",
        ["thread_id"],
        unique=False,
        schema="agent_v1",
    )
    op.create_table(
        "intent_tracking",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.String(length=100), nullable=False),
        sa.Column("thread_id", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("last_updated_by", sa.String(length=50), nullable=False),
        sa.Column("last_intent_model", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("customer_id", "thread_id", name="uq_intent_tracking_customer_thread"),
        schema="agent_v1",
    )
    op.create_index(
        op.f("ix_agent_v1_intent_tracking_created_at"),
        "intent_tracking",
        ["created_at"],
        unique=False,
        schema="agent_v1",
    )
    op.create_index(
        op.f("ix_agent_v1_intent_tracking_customer_id"),
        "intent_tracking",
        ["customer_id"],
        unique=False,
        schema="agent_v1",
    )
    op.create_index(
        op.f("ix_agent_v1_intent_tracking_thread_id"),
        "intent_tracking",
        ["thread_id"],
        unique=False,
        schema="agent_v1",
    )
    op.create_table(
        "sales_intent_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.String(length=100), nullable=False),
        sa.Column("thread_id", sa.String(length=100), nullable=False),
        sa.Column("primary_intent", sa.String(length=50), nullable=False),
        sa.Column("secondary_intents", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("urgency_level", sa.String(length=20), nullable=True),
        sa.Column("budget_range", sa.String(length=100), nullable=True),
        sa.Column("product_interest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("decision_timeline", sa.String(length=200), nullable=True),
        sa.Column("contact_preference", sa.String(length=50), nullable=True),
        sa.Column("extraction_model", sa.String(length=100), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("was_skipped", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="agent_v1",
    )
    op.create_index(
        op.f("ix_agent_v1_sales_intent_logs_created_at"),
        "sales_intent_logs",
        ["created_at"],
        unique=False,
        schema="agent_v1",
    )
    op.create_index(
        op.f("ix_agent_v1_sales_intent_logs_customer_id"),
        "sales_intent_logs",
        ["customer_id"],
        unique=False,
        schema="agent_v1",
    )
    op.create_index(
        op.f("ix_agent_v1_sales_intent_logs_thread_id"),
        "sales_intent_logs",
        ["thread_id"],
        unique=False,
        schema="agent_v1",
    )
    op.create_index(
        "ix_sales_intent_logs_customer_thread",
        "sales_intent_logs",
        ["customer_id", "thread_id"],
        unique=False,
        schema="agent_v1",
    )
    op.create_table(
        "semantic_memory",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.String(length=100), nullable=False),
        sa.Column("summary_id", sa.UUID(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
        sa.Column("embedding_model", sa.String(length=100), nullable=False),
        sa.Column("embedding_dimension", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["summary_id"], ["agent_v1.conversation_summaries.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "summary_id", "embedding_model", name="uq_semantic_memory_summary_model"
        ),
        schema="agent_v1",
    )
    op.create_index(
        "idx_semantic_memory_embedding",
        "semantic_memory",
        ["embedding"],
        unique=False,
        schema="agent_v1",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": 16, "ef_construction": 64},
    )
    op.create_index(
        op.f("ix_agent_v1_semantic_memory_created_at"),
        "semantic_memory",
        ["created_at"],
        unique=False,
        schema="agent_v1",
    )
    op.create_index(
        op.f("ix_agent_v1_semantic_memory_customer_id"),
        "semantic_memory",
        ["customer_id"],
        unique=False,
        schema="agent_v1",
    )
    op.drop_table("checkpoint_migrations")
    op.drop_index(op.f("checkpoint_blobs_thread_id_idx"), table_name="checkpoint_blobs")
    op.drop_table("checkpoint_blobs")
    op.drop_index(op.f("checkpoint_writes_thread_id_idx"), table_name="checkpoint_writes")
    op.drop_table("checkpoint_writes")
    op.drop_index(op.f("checkpoints_thread_id_idx"), table_name="checkpoints")
    op.drop_table("checkpoints")
    op.drop_index(
        op.f("ix_hitl_metadata_status_paused"), table_name="hitl_metadata", schema="agent_v1"
    )
    op.drop_index(
        op.f("idx_products_content_tsvector"),
        table_name="products",
        schema="agent_v1",
        postgresql_using="gin",
    )
    op.drop_column("products", "content_tsvector", schema="agent_v1")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "content_tsvector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "(setweight(to_tsvector('simple'::regconfig, agent_v1.immutable_unaccent((COALESCE(name, ''::character varying))::text)), 'A'::\"char\") || setweight(to_tsvector('simple'::regconfig, agent_v1.immutable_unaccent(COALESCE(description, ''::text))), 'B'::\"char\"))",  # noqa: E501
                persisted=True,
            ),
            autoincrement=False,
            nullable=True,
        ),
        schema="agent_v1",
    )
    op.create_index(
        op.f("idx_products_content_tsvector"),
        "products",
        ["content_tsvector"],
        unique=False,
        schema="agent_v1",
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_hitl_metadata_status_paused"),
        "hitl_metadata",
        ["status", "paused_at"],
        unique=False,
        schema="agent_v1",
    )
    op.create_table(
        "checkpoints",
        sa.Column("thread_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "checkpoint_ns",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("checkpoint_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("parent_checkpoint_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("type", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "checkpoint",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "thread_id", "checkpoint_ns", "checkpoint_id", name=op.f("checkpoints_pkey")
        ),
    )
    op.create_index(op.f("checkpoints_thread_id_idx"), "checkpoints", ["thread_id"], unique=False)
    op.create_table(
        "checkpoint_writes",
        sa.Column("thread_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "checkpoint_ns",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("checkpoint_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("task_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("idx", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("channel", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("type", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("blob", postgresql.BYTEA(), autoincrement=False, nullable=False),
        sa.Column(
            "task_path",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "thread_id",
            "checkpoint_ns",
            "checkpoint_id",
            "task_id",
            "idx",
            name=op.f("checkpoint_writes_pkey"),
        ),
    )
    op.create_index(
        op.f("checkpoint_writes_thread_id_idx"), "checkpoint_writes", ["thread_id"], unique=False
    )
    op.create_table(
        "checkpoint_blobs",
        sa.Column("thread_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "checkpoint_ns",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("channel", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("version", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("type", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("blob", postgresql.BYTEA(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "thread_id", "checkpoint_ns", "channel", "version", name=op.f("checkpoint_blobs_pkey")
        ),
    )
    op.create_index(
        op.f("checkpoint_blobs_thread_id_idx"), "checkpoint_blobs", ["thread_id"], unique=False
    )
    op.create_table(
        "checkpoint_migrations",
        sa.Column("v", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("v", name=op.f("checkpoint_migrations_pkey")),
    )
    op.drop_index(
        op.f("ix_agent_v1_semantic_memory_customer_id"),
        table_name="semantic_memory",
        schema="agent_v1",
    )
    op.drop_index(
        op.f("ix_agent_v1_semantic_memory_created_at"),
        table_name="semantic_memory",
        schema="agent_v1",
    )
    op.drop_index(
        "idx_semantic_memory_embedding",
        table_name="semantic_memory",
        schema="agent_v1",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": 16, "ef_construction": 64},
    )
    op.drop_table("semantic_memory", schema="agent_v1")
    op.drop_index(
        "ix_sales_intent_logs_customer_thread", table_name="sales_intent_logs", schema="agent_v1"
    )
    op.drop_index(
        op.f("ix_agent_v1_sales_intent_logs_thread_id"),
        table_name="sales_intent_logs",
        schema="agent_v1",
    )
    op.drop_index(
        op.f("ix_agent_v1_sales_intent_logs_customer_id"),
        table_name="sales_intent_logs",
        schema="agent_v1",
    )
    op.drop_index(
        op.f("ix_agent_v1_sales_intent_logs_created_at"),
        table_name="sales_intent_logs",
        schema="agent_v1",
    )
    op.drop_table("sales_intent_logs", schema="agent_v1")
    op.drop_index(
        op.f("ix_agent_v1_intent_tracking_thread_id"),
        table_name="intent_tracking",
        schema="agent_v1",
    )
    op.drop_index(
        op.f("ix_agent_v1_intent_tracking_customer_id"),
        table_name="intent_tracking",
        schema="agent_v1",
    )
    op.drop_index(
        op.f("ix_agent_v1_intent_tracking_created_at"),
        table_name="intent_tracking",
        schema="agent_v1",
    )
    op.drop_table("intent_tracking", schema="agent_v1")
    op.drop_index(
        op.f("ix_agent_v1_conversation_summaries_thread_id"),
        table_name="conversation_summaries",
        schema="agent_v1",
    )
    op.drop_index(
        op.f("ix_agent_v1_conversation_summaries_customer_id"),
        table_name="conversation_summaries",
        schema="agent_v1",
    )
    op.drop_index(
        op.f("ix_agent_v1_conversation_summaries_created_at"),
        table_name="conversation_summaries",
        schema="agent_v1",
    )
    op.drop_table("conversation_summaries", schema="agent_v1")
    # ### end Alembic commands ###
