"""initial_schema

Revision ID: 3cdbb9552f4b
Revises:
Create Date: 2026-02-13 23:20:19.093375

"""

from typing import Sequence, Union

import pgvector
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3cdbb9552f4b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(length=100), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="agent_v1",
    )
    op.create_index(
        op.f("ix_agent_v1_conversation_sessions_external_id"),
        "conversation_sessions",
        ["external_id"],
        unique=True,
        schema="agent_v1",
    )
    op.create_table(
        "products",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sku", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="agent_v1",
    )
    op.create_index(
        op.f("ix_agent_v1_products_sku"),
        "products",
        ["sku"],
        unique=True,
        schema="agent_v1",
    )
    op.create_table(
        "semantic_cache",
        sa.Column("query_hash", sa.String(length=64), nullable=False),
        sa.Column("query_text", sa.Text(), nullable=False),
        sa.Column("response", sa.Text(), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False
        ),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("similarity_score", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("query_hash"),
        schema="agent_v1",
    )
    op.create_index(
        "idx_semantic_cache_embedding",
        "semantic_cache",
        ["embedding"],
        unique=False,
        schema="agent_v1",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_table(
        "conversation_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("model_name", sa.String(length=100), nullable=True),
        sa.Column(
            "source_chunk_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["agent_v1.conversation_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="agent_v1",
    )
    op.create_table(
        "text_embeddings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False
        ),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("model_version", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["agent_v1.products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="agent_v1",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("text_embeddings", schema="agent_v1")
    op.drop_table("conversation_messages", schema="agent_v1")
    op.drop_index(
        "idx_semantic_cache_embedding",
        table_name="semantic_cache",
        schema="agent_v1",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("semantic_cache", schema="agent_v1")
    op.drop_index(
        op.f("ix_agent_v1_products_sku"), table_name="products", schema="agent_v1"
    )
    op.drop_table("products", schema="agent_v1")
    op.drop_index(
        op.f("ix_agent_v1_conversation_sessions_external_id"),
        table_name="conversation_sessions",
        schema="agent_v1",
    )
    op.drop_table("conversation_sessions", schema="agent_v1")
    # ### end Alembic commands ###
