"""add_sales_signals_and_model_traces

Revision ID: dcd5e99fdf41
Revises: 87456b64657a
Create Date: 2026-02-25 23:17:07.236529

"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "dcd5e99fdf41"
down_revision: str | Sequence[str] | None = "87456b64657a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sales_signals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("signal_type", sa.String(length=50), nullable=False),
        sa.Column("signal_value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["agent_v1.conversation_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="agent_v1",
    )
    op.create_index(
        op.f("ix_agent_v1_sales_signals_signal_type"),
        "sales_signals",
        ["signal_type"],
        unique=False,
        schema="agent_v1",
    )
    op.create_table(
        "model_traces",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=True),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column("cost", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["agent_v1.conversation_messages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="agent_v1",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("model_traces", schema="agent_v1")
    op.drop_index(
        op.f("ix_agent_v1_sales_signals_signal_type"),
        table_name="sales_signals",
        schema="agent_v1",
    )
    op.drop_table("sales_signals", schema="agent_v1")
    # ### end Alembic commands ###
